python_library(
  name = "tosh",
  sources = rglobs("*.py"),
  dependencies = [
    pants('src/python/twitter/common/lang'),
    pants('src/python/twitter/common/log'),
    pants('3rdparty/python:sqlparse'),
  ]
)

