python_binary(
  name = 'tosh',
  source = 'tosh.py',
  dependencies = [
    pants('src/python/twitter/common/lang'),
    pants('src/python/twitter/common/log'),
    pants('3rdparty/python:sqlparse'),
  ]
)

